spring:
  datasource:
    url: jdbc:mysql://139.224.50.146:3306/qp_database?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    username: sa
    password: 114514
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.163.com
    username: ruangong202105@163.com
    password: NYTIRYOWHUTHAPIS
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        debug: true
    protocol: smtp
    port: 587

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.buaa.qp.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
server:
  port: 8090
  tomcat:
    remoteip:
      remote-ip-header: X-Real-IP
      protocol-header: X-Forwarded-Proto

admin:
  username: lbh
  password: 114514

check:
  ip-address : http://139.224.50.146:8090
  valid-time: 600000
  code-bits: 32

file:
  articles-path: C:/ops/backend/storage
  logs-path: C:/ops/backend
  allow-types: pdf, doc, docx, zip
